### ISSUE TITLE
Need help setting up repo on local machine for ML baseball project

### ISSUE THREAD

**Issue by DevRabb** [arnavsinghvi11/MLB_Betting_Model#1]
Hello,

I hope this message finds you well. I've been exploring your repository and I'm thoroughly impressed with the depth and organization of the materials you've put together for ML in baseball. It's truly one of the most detailed and well-oriented repositories I've come across in this domain.

I've been attempting to get the repository up and running on my local machine so I can delve deeper into the code and perhaps integrate some of your methodologies into my own projects. However, I've encountered some difficulties while trying to set it up, and I was hoping you could provide some guidance.

Here's what I've tried so far:

- Simply running each py file, checked for errors that may have happened while playing with it on my machine.
- Played around in VS Code just trying to figure out exactly where it would be I would need to start to grabbing predictions(Have at the moment 2 different ML models so was looking to compare the picks between the 3 and lets be serious test its luck)

Unfortunately, I seem to be stuck at [describe where you're encountering the issue or error message]. I believe I might be missing something crucial in the setup process, and I was wondering if you could point me in the right direction.
Could you please provide some guidance on how to properly set up the repository on my machine? Any help or pointers you could offer would be greatly appreciated.

Thank you in advance for your assistance. I'm really excited about the potential of integrating your methodologies into my own projects, and I'm looking forward to getting the repository up and running smoothly on my machine.

-Rabb

**Comment by arnavsinghvi11** [comment]
sent out an email to you!
